### PR TITLE
Enforce String type for String concatenation

### LINKED ISSUE #760: Fail compilation when developer tries to concatenate string with other type
An example of this problem is the following:
Developers often want to concatenate strings with integers to print an event, log, or exception message. But, the neow3j compiler does not support string concatenation with other types as Java does.

So either we add extra functionality such that the compiler supports such concatenations or we make it clear at compile-time that it is not supported by throwing a compiler exception.

### PR DESCRIPTION
**Pull request by mialbu**
Closes #760

### CODE REVIEW

File: compiler/src/test-integration/java/io/neow3j/compiler/StringConcatenationTest.java [hunk 1]
```diff
@@ -64,6 +98,31 @@ public static String concatInStaticVariable() {
             return staticString;
         }
 
+        public static String concatStringWithMethodReturn() {
```
Comment (gsmachado) [inline compiler/src/test-integration/java/io/neow3j/compiler/StringConcatenationTest.java:101]: does it worth adding tests with all Java built-in raw types?

Like: `int` (we already have test for this), `byte`, `short`, `long`, `float`, `double`, `boolean`, and `char`? 

Also, maybe, array of these types?

wdyt?

**Review by gsmachado — COMMENTED** [review]
Before I approve: just a question about tests. 😄

File: compiler/src/test-integration/java/io/neow3j/compiler/StringConcatenationTest.java (hunk 1 above)
Comment (mialbu) [reply compiler/src/test-integration/java/io/neow3j/compiler/StringConcatenationTest.java:149]: @gsmachado 
- Trying to concatenate arrays (except `byte[]`) results in an exception on the NeoVM (`Specified cast is not valid`). Therefore, no array types can be used in string concatenations in neow3j. I have added a UT for this in the class `StringLiteralHelperTest.java`.

- `byte`, `byte[]`, `long`, `short` all have the same behaviour as `int`. There are UTs in place for `int` concatenation with strings that are expected to throw an exception. Hence, there's no need to have more tests for these types atm.

- `char` works the same way as `String`. I've added integration tests for the primitive type as well as for the wrapper class (`java/lang/Character`).

- Last but not least: Neow3j does not support float and double in the first place. So, no need for further tests there. The compilation would fail as soon as it notices such types present anyways.

Comment (gsmachado) [reply compiler/src/test-integration/java/io/neow3j/compiler/StringConcatenationTest.java:149]: great! All fine, then.

**Review by gsmachado — APPROVED** [review]
Everything is clear now. 🎉  Ready to go. 💪
